DROP DATABASE test_totesys;

CREATE DATABASE test_totesys;

\c test_totesys

CREATE TABLE "sales_order" (
  "sales_order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (current_timestamp),
  "last_updated" timestamp NOT NULL DEFAULT (current_timestamp),
  "design_id" int NOT NULL,
  "staff_id" int NOT NULL,
  "counterparty_id" int NOT NULL,
  "units_sold" int NOT NULL,
  "unit_price" numeric NOT NULL,
  "currency_id" int NOT NULL,
  "agreed_delivery_date" varchar NOT NULL,
  "agreed_payment_date" varchar NOT NULL,
  "agreed_delivery_location_id" int NOT NULL
);

CREATE TABLE "design" (
  "design_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (current_timestamp),
  "last_updated" timestamp NOT NULL DEFAULT (current_timestamp),
  "design_name" varchar NOT NULL,
  "file_location" varchar NOT NULL,
  "file_name" varchar NOT NULL
);

CREATE TABLE "currency" (
  "currency_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "currency_code" varchar(3) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (current_timestamp),
  "last_updated" timestamp NOT NULL DEFAULT (current_timestamp)
);

CREATE TABLE "staff" (
  "staff_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "department_id" int NOT NULL,
  "email_address" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (current_timestamp),
  "last_updated" timestamp NOT NULL DEFAULT (current_timestamp)
);

CREATE TABLE "counterparty" (
  "counterparty_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "counterparty_legal_name" varchar NOT NULL,
  "legal_address_id" int NOT NULL,
  "commercial_contact" varchar,
  "delivery_contact" varchar,
  "created_at" timestamp NOT NULL DEFAULT (current_timestamp),
  "last_updated" timestamp NOT NULL DEFAULT (current_timestamp)
);

CREATE TABLE "address" (
  "address_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "address_line_1" varchar NOT NULL,
  "address_line_2" varchar,
  "district" varchar,
  "city" varchar NOT NULL,
  "postal_code" varchar NOT NULL,
  "country" varchar NOT NULL,
  "phone" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (current_timestamp),
  "last_updated" timestamp NOT NULL DEFAULT (current_timestamp)
);

CREATE TABLE "department" (
  "department_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "department_name" varchar NOT NULL,
  "location" varchar,
  "manager" varchar,
  "created_at" timestamp NOT NULL DEFAULT (current_timestamp),
  "last_updated" timestamp NOT NULL DEFAULT (current_timestamp)
);

CREATE TABLE "purchase_order" (
  "purchase_order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (current_timestamp),
  "last_updated" timestamp NOT NULL DEFAULT (current_timestamp),
  "staff_id" int NOT NULL,
  "counterparty_id" int NOT NULL,
  "item_code" varchar NOT NULL,
  "item_quantity" int NOT NULL,
  "item_unit_price" numeric NOT NULL,
  "currency_id" int NOT NULL,
  "agreed_delivery_date" varchar NOT NULL,
  "agreed_payment_date" varchar NOT NULL,
  "agreed_delivery_location_id" int NOT NULL
);

CREATE TABLE "payment_type" (
  "payment_type_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "payment_type_name" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (current_timestamp),
  "last_updated" timestamp NOT NULL DEFAULT (current_timestamp)
);

CREATE TABLE "payment" (
  "payment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (current_timestamp),
  "last_updated" timestamp NOT NULL DEFAULT (current_timestamp),
  "transaction_id" int NOT NULL,
  "counterparty_id" int NOT NULL,
  "payment_amount" numeric NOT NULL,
  "currency_id" int NOT NULL,
  "payment_type_id" int NOT NULL,
  "paid" boolean NOT NULL,
  "payment_date" varchar NOT NULL,
  "company_ac_number" int NOT NULL,
  "counterparty_ac_number" int NOT NULL
);

CREATE TABLE "transaction" (
  "transaction_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "transaction_type" varchar NOT NULL,
  "sales_order_id" int,
  "purchase_order_id" int,
  "created_at" timestamp NOT NULL DEFAULT (current_timestamp),
  "last_updated" timestamp NOT NULL DEFAULT (current_timestamp)
);

COMMENT ON COLUMN "sales_order"."units_sold" IS 'value 1000 - 100000';

COMMENT ON COLUMN "sales_order"."unit_price" IS 'value 2.00 - 4.00';

COMMENT ON COLUMN "sales_order"."agreed_delivery_date" IS 'format is yyyy-mm-dd';

COMMENT ON COLUMN "sales_order"."agreed_payment_date" IS 'format is yyyy-mm-dd';

COMMENT ON COLUMN "design"."file_location" IS 'directory location';

COMMENT ON COLUMN "design"."file_name" IS 'file name';

COMMENT ON COLUMN "currency"."currency_code" IS 'three letter code eg GBP';

COMMENT ON COLUMN "staff"."email_address" IS 'must be valid email address';

COMMENT ON COLUMN "counterparty"."commercial_contact" IS 'person name, nullable';

COMMENT ON COLUMN "counterparty"."delivery_contact" IS 'person name, nullable';

COMMENT ON COLUMN "address"."address_line_2" IS 'nullable';

COMMENT ON COLUMN "address"."district" IS 'nullable';

COMMENT ON COLUMN "address"."phone" IS 'valid phone number';

COMMENT ON COLUMN "department"."location" IS 'nullable';

COMMENT ON COLUMN "department"."manager" IS 'nullable';

COMMENT ON COLUMN "purchase_order"."item_quantity" IS 'value between 1 and 1000';

COMMENT ON COLUMN "purchase_order"."item_unit_price" IS 'value 3-1000';

COMMENT ON COLUMN "purchase_order"."agreed_delivery_date" IS 'format is yyyy-mm-dd';

COMMENT ON COLUMN "purchase_order"."agreed_payment_date" IS 'format is yyyy-mm-dd';

COMMENT ON COLUMN "payment_type"."payment_type_name" IS 'one of SALES_RECEIPT SALESREFUND PURCHASE_PAYMENT PURCHASE REFUND';

COMMENT ON COLUMN "payment"."payment_amount" IS 'value 1 - 1000000';

COMMENT ON COLUMN "payment"."payment_date" IS 'format is yyyy-mm-dd';

COMMENT ON COLUMN "payment"."company_ac_number" IS '8 digits';

COMMENT ON COLUMN "payment"."counterparty_ac_number" IS '8 digits';

COMMENT ON COLUMN "transaction"."transaction_type" IS 'one of SALE or PURCHASE';

COMMENT ON COLUMN "transaction"."sales_order_id" IS 'nullable depending on transaction type';

COMMENT ON COLUMN "transaction"."purchase_order_id" IS 'nullable depending on transaction type';

-- ALTER TABLE "sales_order" ADD FOREIGN KEY ("design_id") REFERENCES "design" ("design_id");

-- ALTER TABLE "sales_order" ADD FOREIGN KEY ("staff_id") REFERENCES "staff" ("staff_id");

-- ALTER TABLE "sales_order" ADD FOREIGN KEY ("counterparty_id") REFERENCES "counterparty" ("counterparty_id");

-- ALTER TABLE "sales_order" ADD FOREIGN KEY ("currency_id") REFERENCES "currency" ("currency_id");

-- ALTER TABLE "sales_order" ADD FOREIGN KEY ("agreed_delivery_location_id") REFERENCES "address" ("address_id");

-- ALTER TABLE "staff" ADD FOREIGN KEY ("department_id") REFERENCES "department" ("department_id");

-- ALTER TABLE "counterparty" ADD FOREIGN KEY ("legal_address_id") REFERENCES "address" ("address_id");

-- ALTER TABLE "purchase_order" ADD FOREIGN KEY ("staff_id") REFERENCES "staff" ("staff_id");

-- ALTER TABLE "purchase_order" ADD FOREIGN KEY ("counterparty_id") REFERENCES "counterparty" ("counterparty_id");

-- ALTER TABLE "purchase_order" ADD FOREIGN KEY ("currency_id") REFERENCES "currency" ("currency_id");

-- ALTER TABLE "purchase_order" ADD FOREIGN KEY ("agreed_delivery_location_id") REFERENCES "address" ("address_id");

-- ALTER TABLE "payment" ADD FOREIGN KEY ("transaction_id") REFERENCES "transaction" ("transaction_id");

-- ALTER TABLE "payment" ADD FOREIGN KEY ("counterparty_id") REFERENCES "counterparty" ("counterparty_id");

-- ALTER TABLE "payment" ADD FOREIGN KEY ("currency_id") REFERENCES "currency" ("currency_id");

-- ALTER TABLE "payment" ADD FOREIGN KEY ("payment_type_id") REFERENCES "payment_type" ("payment_type_id");

-- ALTER TABLE "transaction" ADD FOREIGN KEY ("sales_order_id") REFERENCES "sales_order" ("sales_order_id");

-- ALTER TABLE "transaction" ADD FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_order" ("purchase_order_id");

INSERT INTO sales_order
(created_at, last_updated, design_id, staff_id, counterparty_id, units_sold, unit_price, currency_id, agreed_delivery_date, agreed_payment_date, agreed_delivery_location_id) 
VALUES
('2023-08-10 09:15:00', '2023-08-10 09:15:00', 101, 12, 45, 100, 25.50, 1, '2023-09-15', '2023-09-01', 3),
('2023-08-11 11:30:00', '2023-08-11 11:30:00', 102, 15, 50, 250, 30.00, 2, '2023-09-20', '2023-09-05', 4),
('2023-08-12 14:45:00', '2023-08-12 14:45:00', 103, 18, 60, 500, 40.75, 3, '2023-09-25', '2023-09-10', 5);

INSERT INTO design 
(created_at, last_updated, design_name, file_location, file_name) 
VALUES
('2023-08-10 10:00:00', '2023-08-10 10:00:00', 'Modern Living Room', '/designs/living_room/', 'modern_living_room_v1.png'),
('2023-08-11 11:30:00', '2023-08-11 11:30:00', 'Contemporary Kitchen', '/designs/kitchen/', 'contemporary_kitchen_v2.jpg'),
('2023-08-12 14:45:00', '2023-08-12 14:45:00', 'Classic Bedroom', '/designs/bedroom/', 'classic_bedroom_v3.svg');

INSERT INTO currency 
(currency_code, created_at, last_updated)
VALUES
('USD', '2023-08-10 09:00:00', '2023-08-10 09:00:00'),
('EUR', '2023-08-11 10:30:00', '2023-08-11 10:30:00'),
('GBP', '2023-08-12 12:00:00', '2023-08-12 12:00:00');

INSERT INTO staff 
(first_name, last_name, department_id, email_address, created_at, last_updated) 
VALUES
('John', 'Doe', 1, 'john.doe@example.com', '2023-08-10 08:00:00', '2023-08-10 08:00:00'),
('Jane', 'Smith', 2, 'jane.smith@example.com', '2023-08-11 09:15:00', '2023-08-11 09:15:00'),
('Robert', 'Johnson', 3, 'robert.johnson@example.com', '2023-08-12 10:30:00', '2023-08-12 10:30:00');

INSERT INTO counterparty 
(counterparty_legal_name, legal_address_id, commercial_contact, delivery_contact, created_at, last_updated) 
VALUES
('Global Corp Ltd', 101, 'Alice Brown', 'Bob White', '2023-08-10 10:00:00', '2023-08-10 10:00:00'),
('Tech Innovators Inc', 102, 'Charlie Green', 'David Black', '2023-08-11 11:15:00', '2023-08-11 11:15:00'),
('Creative Solutions LLC', 103, 'Eve Blue', 'Frank Yellow', '2023-08-12 12:30:00', '2023-08-12 12:30:00');

INSERT INTO address 
(address_line_1, address_line_2, district, city, postal_code, country, phone, created_at, last_updated) 
VALUES
('123 Main St', 'Apt 4B', 'Downtown', 'Manchester', 'M1 1AA', 'UK', '01234 567890', '2023-08-10 08:00:00', '2023-08-10 08:00:00'),
('456 Elm St', NULL, 'Northside', 'Leeds', 'LS1 2BB', 'UK', '09876 543210', '2023-08-11 09:15:00', '2023-08-11 09:15:00'),
('789 Oak St', 'Suite 300', NULL, 'Liverpool', 'L3 4CC', 'UK', '01122 334455', '2023-08-12 10:30:00', '2023-08-12 10:30:00');

INSERT INTO purchase_order 
(staff_id, counterparty_id, item_code, item_quantity, item_unit_price, currency_id, agreed_delivery_date, agreed_payment_date, agreed_delivery_location_id, created_at, last_updated) 
VALUES
(12, 45, 'ITEM001', 100, 15.75, 1, '2023-09-15', '2023-09-01', 3, '2023-08-10 08:00:00', '2023-08-10 08:00:00'),
(15, 50, 'ITEM002', 200, 22.50, 2, '2023-09-20', '2023-09-05', 4, '2023-08-11 09:15:00', '2023-08-11 09:15:00'),
(18, 60, 'ITEM003', 150, 30.00, 3, '2023-09-25', '2023-09-10', 5, '2023-08-12 10:30:00', '2023-08-12 10:30:00');

INSERT INTO department 
(department_name, location, manager, created_at, last_updated) 
VALUES
('Human Resources', 'New York', 'Alice Johnson', '2023-08-10 08:00:00', '2023-08-10 08:00:00'),
('IT Support', 'San Francisco', 'Bob Smith', '2023-08-11 09:15:00', '2023-08-11 09:15:00'),
('Marketing', 'Chicago', 'Carol Davis', '2023-08-12 10:30:00', '2023-08-12 10:30:00');

INSERT INTO payment_type 
(payment_type_name, created_at, last_updated) 
VALUES
('Credit Card', '2023-08-10 08:00:00', '2023-08-10 08:00:00'),
('Bank Transfer', '2023-08-11 09:15:00', '2023-08-11 09:15:00'),
('PayPal', '2023-08-12 10:30:00', '2023-08-12 10:30:00');

INSERT INTO payment 
(transaction_id, counterparty_id, payment_amount, currency_id, payment_type_id, paid, payment_date, company_ac_number, counterparty_ac_number, created_at, last_updated) 
VALUES
(1, 45, 552548.62, 1, 3, true, '2023-09-04', 67305075, 31622269, '2023-08-10 08:00:00', '2023-08-10 08:00:00'),
(2, 50, 205952.22, 2, 1, false, '2023-09-05', 81718079, 47839086, '2023-08-11 09:15:00', '2023-08-11 09:15:00'),
(3, 60, 57067.20, 3, 2, true, '2023-09-10', 66213052, 91659548, '2023-08-12 10:30:00', '2023-08-12 10:30:00');

INSERT INTO transaction 
(transaction_type, sales_order_id, purchase_order_id, created_at, last_updated) 
VALUES
('Sale', 1, NULL, '2023-08-10 08:00:00', '2023-08-10 08:00:00'),
('Purchase', NULL, 101, '2023-08-11 09:15:00', '2023-08-11 09:15:00'),
('Refund', 2, NULL, '2023-08-12 10:30:00', '2023-08-12 10:30:00');

SELECT * FROM sales_order;

SELECT * FROM design;

SELECT * FROM currency;

SELECT * FROM staff;

SELECT * FROM counterparty;

SELECT * FROM address;

SELECT * FROM purchase_order;

SELECT * FROM department;

SELECT * FROM payment_type;

SELECT * FROM payment;

SELECT * FROM transaction;